import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

# Window dimensions
[window]
dimensions.columns = 100
dimensions.lines = 30
position.x = 0
position.y = 0
padding.x = 0
padding.y = 0
dynamic_padding = false
decorations = "none"
startup_mode = "Windowed"

# Font configuration
[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font Mono"
bold.style = "Bold"
italic.family = "JetBrainsMono Nerd Font Mono"
italic.style = "Italic"
size = 12.0
offset.x = 0
offset.y = 0
glyph_offset.x = 0
glyph_offset.y = 0

# Scrolling
[scrolling]
history = 10000
multiplier = 3

# Key bindings
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Q"
mods = "Control|Shift"
action = "Quit"

# Cursor
[cursor]
style = "Block"
unfocused_hollow = true

# Shell
[shell]
program = "/usr/bin/tmux"
args = ["new-session"]

# Environmen
[env]
TERM = "xterm-256color"

