# Alacritty Configuration File
# Colors
[colors]

# Default colors
[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

# Normal colors
[colors.normal]
black   = "#32344a"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#ad8ee6"
cyan    = "#449dab"
white   = "#787c99"

# Bright colors
[colors.bright]
black   = "#444b6a"
red     = "#ff7a93"
green   = "#b9f27c"
yellow  = "#ff9e64"
blue    = "#7da6ff"
magenta = "#bb9af7"
cyan    = "#0db9d7"
white   = "#acb0d0"

# Dim colors (optional)
[colors.dim]
# ... (Se desejar, adicione cores dim aqui)

# Indexed colors (optional)
[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

# Cursor colors
[colors.cursor]
text = "0x1e1e2e"
cursor = "0xf5e0dc"

[colors.vi_mode_cursor]
text = "0x1e1e2e"
cursor = "0xb4befe"

# Window dimensions
[window]
dimensions.columns = 100
dimensions.lines = 30
position.x = 0
position.y = 0
padding.x = 0
padding.y = 0
dynamic_padding = false
decorations = "none"
startup_mode = "Windowed"

# Font configuration
[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font Mono"
bold.style = "Bold"
italic.family = "JetBrainsMono Nerd Font Mono"
italic.style = "Italic"
size = 12.0
offset.x = 0
offset.y = 0
glyph_offset.x = 0
glyph_offset.y = 0

# Scrolling
[scrolling]
history = 10000
multiplier = 3

# Key bindings
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Q"
mods = "Control|Shift"
action = "Quit"

# Cursor
[cursor]
style = "Block"
unfocused_hollow = true

# Shell
[shell]
program = "/usr/bin/tmux"
args = ["new-session"]

# Environmen
[env]
TERM = "xterm-256color"
