# Alacritty Configuration File

# Window dimensions
[window]
dimensions.columns = 100
dimensions.lines = 30
position.x = 0
position.y = 0
padding.x = 0
padding.y = 0
dynamic_padding = false
decorations = "none"
startup_mode = "Windowed"

# Font configuration
[font]
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Regular"
bold.family = "JetBrainsMono Nerd Font Mono"
bold.style = "Bold"
italic.family = "JetBrainsMono Nerd Font Mono"
italic.style = "Italic"
size = 12.0
offset.x = 0
offset.y = 0
glyph_offset.x = 0
glyph_offset.y = 0

# Scrolling
[scrolling]
history = 10000
multiplier = 3

# Key bindings
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Q"
mods = "Control|Shift"
action = "Quit"

# Colors (Catppuccin Mocha theme)
[colors]
[colors.primary]
background = "0x1e1e2e"
foreground = "0xcdd6f4"
dim_foreground = "0x7f849c"
bright_foreground = "0xcdd6f4"

[colors.cursor]
text = "0x1e1e2e"
cursor = "0xf5e0dc"

[colors.vi_mode_cursor]
text = "0x1e1e2e"
cursor = "0xb4befe"

[colors.search.matches]
foreground = "0x1e1e2e"
background = "0xa6adc8"

[colors.search.focused_match]
foreground = "0x1e1e2e"
background = "0xa6e3a1"

[colors.footer_bar]
foreground = "0x1e1e2e"
background = "0xa6adc8"

[colors.hints.start]
foreground = "0x1e1e2e"
background = "0xf9e2af"

[colors.hints.end]
foreground = "0x1e1e2e"
background = "0xa6adc8"

[colors.selection]
text = "0x1e1e2e"
background = "0xf5e0dc"

[colors.normal]
black = "0x45475a"
red = "0xf38ba8"
green = "0xa6e3a1"
yellow = "0xf9e2af"
blue = "0x89b4fa"
magenta = "0xf5c2e7"
cyan = "0x94e2d5"
white = "0xbac2de"

[colors.bright]
black = "0x585b70"
red = "0xf38ba8"
green = "0xa6e3a1"
yellow = "0xf9e2af"
blue = "0x89b4fa"
magenta = "0xf5c2e7"
cyan = "0x94e2d5"
white = "0xa6adc8"

[colors.dim]
black = "0x45475a"
red = "0xf38ba8"
green = "0xa6e3a1"
yellow = "0xf9e2af"
blue = "0x89b4fa"
magenta = "0xf5c2e7"
cyan = "0x94e2d5"
white = "0xbac2de"

[[colors.indexed_colors]]
index = 16
color = "0xfab387"

[[colors.indexed_colors]]
index = 17
color = "0xf5e0dc"

# Cursor
[cursor]
style = "Block"
unfocused_hollow = true

# Shell
[shell]
program = "/usr/bin/tmux"
args = ["new-session"]

# Environmen
[env]
TERM = "xterm-256color"
